# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02dfb9663ddace04873b19a158afddee97b3034f771c6cc9f3157194dc28b1f2a21452aac9bc62f680fec1592d26549ea822651069281dad3907888d860e403f

test:
  secret_key_base: c9b4afba4736e24aab2699838cd4fffe73a3b05e28880c95a32db60ef38050f6700b277268add069a9184c8703077545b5c11bf415ca06c762ad687d9beb7254

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
